export const SWITCH_ORDER_TYPE = "SWITCH_ORDER_TYPE";
export const GET_CHART_DATA = "GET_CHART_DATA";

export const EXCHANGE_LOADED = "EXCHANGE_LOADED";
export const EXCHANGE_LOGIN = "EXCHANGE_LOGIN";
export const EXCHANGE_CURRENT_MARKET = "EXCHANGE_CURRENT_MARKET";
