export const EXCHANGE_LOADED = "EXCHANGE_LOADED";
export const EXCHANGE_LOAD_SELLBOOK = "EXCHANGE_LOAD_SELLBOOK";
export const EXCHANGE_LOAD_BUYBOOK = "EXCHANGE_LOAD_BUYBOOK";
export const EXCHANGE_LOAD_TICKS = "EXCHANGE_LOAD_TICKS";
export const EXCHANGE_LOAD_TRADES = "EXCHANGE_LOAD_TRADES";
export const EXCHANGE_LOGIN = "EXCHANGE_LOGIN";
export const EXCHANGE_CURRENT_MARKET = "EXCHANGE_CURRENT_MARKET";
