export const SWITCH_ORDER_TYPE = "SWITCH_ORDER_TYPE";
export const GET_CHART_DATA = "GET_CHART_DATA";
export const EXCHANGE_CONNECT = "EXCHANGE_CONNECT";
export const EXCHANGE_LOGIN = "EXCHANGE_LOGIN";
